<?php 
$acao=$_GET['acao'];
//$id=$_GET['id'];
$id=(isset($_GET['id']))?$_GET['id']:"0";
switch ($acao){
	case 'formcadastro':
	$form=new Form("professor");
	$form->FormCadastro('','cadastrar');	
	break;
	
	case 'cadastrar':
	$professors=new professors("");
	$professors->Cadastrar();
	break;
	
	case 'listar':
	$professors=new professors();
	$professors->Listar();
	break;
	
	case 'deletar':
	$professors=new professors();
	$professors->Deletar($id);
	break;
	
	case 'formeditar':
	$form=new Form("professor");
	$form->FormEditar("editar",$id);
	break;
	
	case 'editar':
	$professors=new professors();
	$professors->Atualizar($id);
	
}


?>